### ISSUE TITLE
Replay strategy on "Alignment-Based Replayer(Default)" not saved correctly from options

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#10]
I found the following problem. Creating the node, the default replay strategy is "ILP" and does not work. Crash as in #3 with NullPointerException. Then I change it to "Non-ILP" and it works. Then I change it again to "ILP" and it works (differently from the first step where it crashes)

I guess something is broken here:
![image](https://user-images.githubusercontent.com/56342194/69608665-3872b800-1028-11ea-8a13-31b01926b9d4.png)

**Comment by KFDing** [comment]
Hi Ale,

which OS do you use?? Windows, or Linux?? Currently, I have enabled it on Windows. For linux, a bit time to wait. 
Regards
Kefang

**Comment by KFDing** [comment]
Hi @fit-alessandro-berti ,
it should work now. Have changed the mechanism to read the strategy. 
Regards
kefang
