### ISSUE TITLE
List of classifiers is hardcoded in "Alignment-Based Replayer(Default)"

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#11]
I have taken the running-example log that has only the name classifier. The Inductive Miner node correctly reportes me only the "Event Name" classifier. While the "Alignment-Based Replayer" proposes also a classifier that does not actually exist in the log:

![image](https://user-images.githubusercontent.com/56342194/69609084-07df4e00-1029-11ea-9a78-d2d2dc31c5d4.png)

Inductive Miner reported instead only the event name:
![image](https://user-images.githubusercontent.com/56342194/69609108-16c60080-1029-11ea-83e0-d79ada313e6e.png)

**Comment by KFDing** [comment]
Hi, have solved the problem with multiple classifiers which are extracted from the event log's classifiers and also its event attributes.  
Regards
Kefang
