### ISSUE TITLE
Feature request - Process Tree from Inductive Miner in Knime

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#21]
I think it changes little to make another node that produces a process tree instead of a Petri net using Inductive Miner

This is important because the default output of IM is a process tree

**Comment by KFDing** [comment]
Hi, Ale,
the previous consideration without process tree is due the use of process tree with another nodes. But definitely, you have the point. Will add such feature in the next release.

**Comment by KFDing** [comment]
Hi, I already added the new feature to output a Process Tree for Inductive Miner. More exactly, the output for Inductive Miner is now a process tree. 
To make it into Petri net, you need to use PT2PN Converter node to convert the Process Tree into Petri net. 
regards
Kefang
