### ISSUE TITLE
Cannot stop jobs with cancel button

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#24]
I have an alignment execution that with DIjkstra is taking ages

Then I want to cancel the job

I click the Cancel button and nothing happens

I guess its safe to somehow implement a mechanism to kill the jobs

**Comment by KFDing** [comment]
Hi, @fit-alessandro-berti ,

you are right. It is a feature that I didn't implement. Now I am trying to add this feature in the new version.

**Comment by KFDing** [comment]
Hi, have implemented the feature to cancel the node. But due to different process, some of the cancellations take a bit long time.
