### ISSUE TITLE
Alignment-Based Replayer(Default) node is obsolete

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4knime/pm4knime-development#25]
The "Alignment-Based Replayer(Default)" is obsolete.
The "Alignment-Based Replayer" already auto updates all the values of the log moves when the edit field of the log moves are changed.
Hence, the "Default" is just a strict subset of the other operator.

**Comment by KFDing** [comment]
Hi, Bas.
due to some programming issue,  let us just keep it in this way. The Alignment-Based Replayer(Default) can be used in repeated loop, while the  node Alignment-Based Replayer can't be used in loop. 

Regards
Kefang
