### ISSUE TITLE
Fitness Checker Operator

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4knime/pm4knime-development#28]
I don't see the point of the Fitness Checker Operator.
It just lists information that is already part of the Alignments, why not just output the table from the "Alignment-Based Replayer"

**Comment by KFDing** [comment]
Hi Bas,

the reasons for separating Fitness Checker are :
1.  to deal with different fitness information from different replayer. 
2.  to generate a view of fitness projection on Petri net from Fitness Checker Operator.  
Without the separate Fitness Checker, it increases the complexity of Alignment Replayer and confuses the successive connection of output Alignment, with Precision and Performance Checker.  Therefore,  the Fitness Checker is separate. 
Hope this answers your question.

Regards
Kefang
