### ISSUE TITLE
NullPointerException when applying alignments on sound workflow net

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#3]
Both with the Alignment-Based Replayer and the "Alignment-Based Replayer(Default)" I get the following error:

![image](https://user-images.githubusercontent.com/56342194/69605799-6d2f4100-1021-11ea-8bb3-90e40161c0d6.png)
![image](https://user-images.githubusercontent.com/56342194/69605809-71f3f500-1021-11ea-9480-57e4a1d68168.png)

**Comment by fit-alessandro-berti** [comment]
With the Non-ILP (Dijkstra?) solver it works, so I think it's just a problem of the DLLs to load (lpsolve etc.)

Albeit, Inductive Miner of ProM falls through often in the parallelism ( :( :( :( ), so it's not feasible ..

**Comment by KFDing** [comment]
I assume it might depend on the event classifier setting. Try the new version and check it.
