### ISSUE TITLE
Out of memory of plugin causes out of memory and crash of the entire application

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#30]
Tried with Alignment (Non-ILP)

The amount of states queued make not only the alignment crash but also the entire Knime

**Comment by KFDing** [comment]
I assume it is because of some loop during the running. Could you send me the exact data and workflow, such that I can have a clearer look at it?

**Comment by KFDing** [comment]
Hi, to avoid the crash in KNIME, one solutionn is to extend the available running memory by 
Optimizing your knime.ini. The knime.ini file sets many options that are used by the Java Virtual Machine when KNIME Analytics Platform is launched.

-Xmx=<memory>g: Editing the line that is present in the knime.ini by default allows you to specify how much RAM KNIME Analytics Platform is allowed to use. If you are only using KNIME Analytics Platform and have 8 GB RAM available, then you can probably set this to 6 GB.

Regards
kefang
