### ISSUE TITLE
Random Classify Event Log does not have a description

### ISSUE THREAD

**Issue by s-j-v-zelst** [pm4knime/pm4knime-development#31]
It is not clear to me what the "random classify event log" operator does.
There is no description of it either.
The operator seems to work.

**Comment by KFDing** [comment]
This node is supposed to classify the event log randomly based on trace variants. Current version just assigns all values as positive or negative. Later, one powerful version will be released to have more choices on it.

**Comment by KFDing** [comment]
Modify the configuration panel for random classify event log.
