### ISSUE TITLE
 (enhancement) Currently, the default event classifier is the timestamp.

### ISSUE THREAD

**Issue by FrankBGao** [pm4knime/pm4knime-development#33]
![image](https://user-images.githubusercontent.com/20436775/73655364-2cd9e800-468e-11ea-8a0a-ac5cf3b35f41.png)
Currently, the default event classifier of discovery algorithms is the timestamp. Could you change it as the concept name. Otherwise, the user need to change it every time.

**Comment by KFDing** [comment]
Hi @FrankBGao ,
thanks for the report. We will improve it as a new feature in the next version. 
Kefang

**Comment by KFDing** [comment]
Hi, I have removed the time-stamp as the default classifier. Now one of the event log default classifiers are set as default.
