### ISSUE TITLE
(UI bug) The Alpha Miner's configeration cannot show the options

### ISSUE THREAD

**Issue by FrankBGao** [pm4knime/pm4knime-development#34]
![image](https://user-images.githubusercontent.com/20436775/73656158-d372b880-468f-11ea-8179-f183fa264fa8.png)

The first time of using this function is fine. After I closed it and opened it again, the options of the event classifier are disappeared. Other miners don't have this issue.

**Comment by FrankBGao** [comment]
The heuristics miner has a similar problem.
![image](https://user-images.githubusercontent.com/20436775/73665793-fc9c4480-46a1-11ea-9aad-2c79a9120232.png)

**Comment by FrankBGao** [comment]
ILP miner has the same problem

![image](https://user-images.githubusercontent.com/20436775/73667980-69fda480-46a5-11ea-96cb-d9a9ef69eaab.png)

**Comment by KFDing** [comment]
Hi, @FrankBGao ,
thanks for the report. I want to ask, does it happen when you drag the node firstly into the workflow? Or you just copy one existing node from old workflow?? 

Regards
Kefang

**Comment by KFDing** [comment]
Hi, please update to the new version, it should fix the problem now.

**Comment by FrankBGao** [comment]
Hi, this is the workflow I modeled
[workflows.zip](https://github.com/pm4knime/pm4knime-development/files/4152165/workflows.zip)

**Comment by KFDing** [comment]
Hi, I have fixed the problem in the new version.  Try it later. 
Kefang
