### ISSUE TITLE
(bug) Table2Xlog function doesn't work

### ISSUE THREAD

**Issue by FrankBGao** [pm4knime/pm4knime-development#35]
This is the workflow I modeled
![image](https://user-images.githubusercontent.com/20436775/73663209-69611000-469d-11ea-9f59-3ace9b947103.png)
This is the data for output
![image](https://user-images.githubusercontent.com/20436775/73663250-7c73e000-469d-11ea-81cb-1385c1a8d16a.png)
It shows there is no data in the output.
I have upload all the file (input and output) in this zip

[issue.zip](https://github.com/pm4knime/pm4knime-development/files/4148479/issue.zip)

**Comment by KFDing** [comment]
Hi, @FrankBGao ,
could you export the KNIME workflow and upload it in the .zip file?? So I can know your settings exactly? Thanks
Kefang

**Comment by KFDing** [comment]
Hi, @FrankBGao ,
I have checked the workflow, you should set the right configuration at Panel called Choose Attribute Set with one requirement that the trace attributes have to hold the same values for all the events. Else, it will have the exception that trace value for all events do not match and no trace is added in your case. 
![image](https://user-images.githubusercontent.com/22542140/73766636-98978000-4776-11ea-86a1-fcc9d0d80c01.png)

I will add more information about the settings. 
Regards
Kefang
