### ISSUE TITLE
(bug) Xlog2Table function doesn't work

### ISSUE THREAD

**Issue by FrankBGao** [pm4knime/pm4knime-development#36]
This the model I made.
![image](https://user-images.githubusercontent.com/20436775/73664501-d1185a80-469f-11ea-9e34-a21934bf297a.png)
The output data is looking like this
![image](https://user-images.githubusercontent.com/20436775/73664568-ec836580-469f-11ea-847b-bb28497d97e5.png)
All the files are in this zip
[Xlog2Table.zip](https://github.com/pm4knime/pm4knime-development/files/4148556/Xlog2Table.zip)

**Comment by KFDing** [comment]
Hi, @FrankBGao ,
with TableWriter from KNIME, it generates a table which is not in txt file!! In this way, it causes the unreadable content. Try to reopen the table with Table Reader, you can check the result. 
Kefang
