### ISSUE TITLE
(bug) Conform check operators fail to run

### ISSUE THREAD

**Issue by FrankBGao** [pm4knime/pm4knime-development#37]
alignment_base_replay(default) and alignment_base_replay fail to run.
I'm not sure that the problem is from my workflow or it's from the operators.
The log is
[knime.log](https://github.com/pm4knime/pm4knime-development/files/4185772/knime.log)
The screenshot is
![image](https://user-images.githubusercontent.com/20436775/74239338-f298c800-4cd7-11ea-9f16-a834af3f1fd7.png)

**Comment by FrankBGao** [comment]
This is the workflow
[alignment_base_replay.zip](https://github.com/pm4knime/pm4knime-development/files/4185939/alignment_base_replay.zip)

**Comment by KFDing** [comment]
Thanks for the report with data, I will have a look at it.

**Comment by KFDing** [comment]
fixed the bugs now.
