### ISSUE TITLE
Alpha Miner crashes

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#38]
Choosing the running-example.xes log file and the Alpha Miner, the Alpha Miner crash through 

ERROR Alpha Miner          2:2        Execute failed: ("NullPointerException"): null

**Comment by fit-alessandro-berti** [comment]
If the configuration window is open, then it works

**Comment by KFDing** [comment]
Hi, since the configuration is open. It suggests that it is due to the configuration problem. Please make sure that you configure the node before you run the node.
