### ISSUE TITLE
NullPointerException when applying DFM Miner to a log

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#4]
As in the picture, the other miners work flawlessy but the DFM Miner no

![image](https://user-images.githubusercontent.com/56342194/69606088-2aba3400-1022-11ea-94a4-07a587659421.png)

**Comment by fit-alessandro-berti** [comment]
Also ILPMiner fails

**Comment by KFDing** [comment]
Seems like lpSolver loading problem,  can you send me the dataset and workflow of this?? Thanks Kefang

**Comment by KFDing** [comment]
should work right now.
