### ISSUE TITLE
ILP miner crashes on running-example.xes

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#40]
![image](https://user-images.githubusercontent.com/56342194/74248046-49f26480-4ce7-11ea-8ca1-111d90983b48.png)

ERROR ILPMiner             2:2        Execute failed: ("NullPointerException"): null

**Comment by fit-alessandro-berti** [comment]
If the configuration window is open, then it works

**Comment by KFDing** [comment]
Hi, since the configuration is open. It suggests that it is due to the configuration problem. Please make sure that you configure the node before you run the node.
