### ISSUE TITLE
DFM Miner crash on running-example

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#42]
![image](https://user-images.githubusercontent.com/56342194/74248379-c9803380-4ce7-11ea-9c69-00a827e9f94a.png)

ERROR DFM Miner            2:2        Execute failed: not found variant type

**Comment by fit-alessandro-berti** [comment]
If the configuration window is open, then it works

**Comment by KFDing** [comment]
Hi, since the configuration is open. It suggests that it is due to the configuration problem. Please make sure that you configure the node before you run the node.
