### ISSUE TITLE
Fitness checking table is strange

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#43]
![image](https://user-images.githubusercontent.com/56342194/74249169-07318c00-4ce9-11ea-9906-bd2ede389de8.png)

Cannot understand it well

![image](https://user-images.githubusercontent.com/56342194/74249070-e2d5af80-4ce8-11ea-86e0-3f14eeab9b6b.png)
![image](https://user-images.githubusercontent.com/56342194/74249087-e79a6380-4ce8-11ea-8d8c-767e1575b5c2.png)
![image](https://user-images.githubusercontent.com/56342194/74249108-ec5f1780-4ce8-11ea-9c7a-e69be0e91cea.png)
![image](https://user-images.githubusercontent.com/56342194/74249122-f08b3500-4ce8-11ea-8aa2-0e383a781e1a.png)

**Comment by KFDing** [comment]
Hi, Ale, I need more details about the "strange" feeling. If you mean the Spec column or the properties table, they are created automatically from KNIME but based on the data of the first table. If it is about the first table, I need to change the table name to make it better.
Kefang

**Comment by KFDing** [comment]
Hi, the fitness information is in the first table.
