### ISSUE TITLE
After changing the log, the alignment node keeps the information of the previous Petri net

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#44]
First I executed everything on the running-example, then changed the log to "receipt" and this is the effect

![image](https://user-images.githubusercontent.com/56342194/74249532-98086780-4ce9-11ea-9959-0cb8fc38fb34.png)

**Comment by fit-alessandro-berti** [comment]
Workflow (that obviously crashes)

![image](https://user-images.githubusercontent.com/56342194/74249633-bec69e00-4ce9-11ea-9a04-c3ae88191a87.png)

**Comment by KFDing** [comment]
Hi, Ale, that's a bug. Have fixed now.
