### ISSUE TITLE
Alignment-based replay crashes on receipt log

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#45]
![image](https://user-images.githubusercontent.com/56342194/74249872-1f55db00-4cea-11ea-9be9-b5e3336aa211.png)

![image](https://user-images.githubusercontent.com/56342194/74249902-28df4300-4cea-11ea-9ea5-324926384be7.png)

ERROR Alignment-Based Replayer 2:8        Execute failed: ("NullPointerException"): null

**Comment by KFDing** [comment]
Hi, could you send me the log and the workflow, so I can have a deeper look at this? Thanks.

**Comment by KFDing** [comment]
Hi, Ale, could you send me the data, event log and  the exported workflow, so I can have a deeper look at it? Thanks

**Comment by KFDing** [comment]
Hi, have checked the bugs and fixed them now.
