### ISSUE TITLE
Table2XLog crashes on parsing the timestamps from XLog2Table obtained from receipt log

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#47]
![image](https://user-images.githubusercontent.com/56342194/74250337-bde23c00-4cea-11ea-977d-576ce6b22788.png)

ERROR Table2XLog Converter 2:3        Execute failed: Text '2011-10-11T13:45:40.276' could not be parsed, unparsed text found at index 0

**Comment by fit-alessandro-berti** [comment]
![image](https://user-images.githubusercontent.com/56342194/74250379-ccc8ee80-4cea-11ea-895e-3c3017f9c8f2.png)

**Comment by KFDing** [comment]
Hi, to convert the Table2Xlog, you need to set the Date Format to parse the time stamp column. Given the right Date format, it should work.
