### ISSUE TITLE
Export XLog does not contain the specified extension

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#48]
Still open

It was closed in #15 but importing/exporting the Receipt log some extensions are still missing

![image](https://user-images.githubusercontent.com/56342194/74250721-511b7180-4ceb-11ea-98b6-da67436ab7a4.png)

![image](https://user-images.githubusercontent.com/56342194/74250741-5a0c4300-4ceb-11ea-8b62-83cd8aac5131.png)

**Comment by KFDing** [comment]
Hi, Ale,
due to the extension is not standard. When you import the event log with OpenNaive strategy, it could read the extensions. Please choose the one called Lenient to read the event log with extension. 
regards
Kefang
