### ISSUE TITLE
Applying XLog2Table and then Table2XLog does not work correctly

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#5]
As in the picture

![image](https://user-images.githubusercontent.com/56342194/69606259-a61be580-1022-11ea-814d-8b844444c756.png)

**Comment by fit-alessandro-berti** [comment]
Error:
ERROR Table2XLog Converter 2:3        Execute failed: Could not find column name:CaseID

**Comment by KFDing** [comment]
Hi @fit-alessandro-berti , 
you need to make sure the configuration settings right at first. After this, it should work now.
