### ISSUE TITLE
"No-ILP Replay" strategy has an error in the "Performance Checker"

### ISSUE THREAD

**Issue by FrankBGao** [pm4knime/pm4knime-development#50]
After alignment_base_replay and alignment_base_replay(default), "Performance Checker"  has error

The replay strategy - "No-ILP Replay" has an error in the "Performance Checker"
![image](https://user-images.githubusercontent.com/20436775/74822229-1924b780-5305-11ea-8a1a-f1577b17c15b.png)
Only "No-ILP Replay" has this problem, other strategies don't have/
![image](https://user-images.githubusercontent.com/20436775/74822213-10cc7c80-5305-11ea-8d18-de3100edbb90.png)

This is the workflow.
[alignment_base_replay.zip](https://github.com/pm4knime/pm4knime-development/files/4224282/alignment_base_replay.zip)
This is the log.
[knime.log](https://github.com/pm4knime/pm4knime-development/files/4224304/knime.log)

**Comment by KFDing** [comment]
Hi, Frank, 
have checked the workflow, You need to configure the timestamp option in Performance Checker at first before you execute the node.  It's a configuration error. 
Kefang
