### ISSUE TITLE
Dotted Chart visualization is not fitting screen (Windows; 1920x1080 resolution)

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#51]
Windows 10

![image](https://user-images.githubusercontent.com/56342194/75883525-70597a80-5e23-11ea-8be2-a56359738a32.png)

**Comment by KFDing** [comment]
When you mean the fitting, it is after you clicking the whole screen button? Or you manually scale the size?

**Comment by fit-alessandro-berti** [comment]
Just opening the dotted chart! I am not using a giant monitor here, only the notebook screen, but the resolution shall still be enough

**Comment by KFDing** [comment]
have changed the view to fit the half of the current screen resolutioon. Now it should work.
