### ISSUE TITLE
Despite selecting IEEE Lenient importer, export does not have all the extensions

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#52]
Log: Receipt

importer:
![image](https://user-images.githubusercontent.com/56342194/75883892-11483580-5e24-11ea-9232-7aa864d97efd.png)

exporting:
![image](https://user-images.githubusercontent.com/56342194/75883909-17d6ad00-5e24-11ea-9669-0553a20c2fbe.png)

**Comment by KFDing** [comment]
Hi, Ale,
thanks for the report. have tracked down and confirmed it is a bug. Will fix it soon.
