### ISSUE TITLE
XLog -> XLog2Table -> Table2XLog not working correctly on receipt log

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#55]
Workflow:
![image](https://user-images.githubusercontent.com/56342194/75885891-a1d44500-5e27-11ea-8ea3-a89747492778.png)

Original log:
![image](https://user-images.githubusercontent.com/56342194/75885942-b57fab80-5e27-11ea-9fa3-150cc6126996.png)

Configuration of the Table2XLog
![image](https://user-images.githubusercontent.com/56342194/75885999-d0522000-5e27-11ea-9f25-263201f6f416.png)

New XLog at the end
![image](https://user-images.githubusercontent.com/56342194/75886042-e364f000-5e27-11ea-844e-7e2b98fe5cb4.png)

![image](https://user-images.githubusercontent.com/56342194/75886062-f24ba280-5e27-11ea-85b4-3dce853f2600.png)

**Comment by fit-alessandro-berti** [comment]
It seems that you inverted the case ID with the event class column!

**Comment by KFDing** [comment]
Hi, Ale,
I have tried at my side. It has no problem. I assume that the configuration might go wrong. Could you send me the workflow you use, such that I can have a test?
Kefang

**Comment by FrankBGao** [comment]
I tested this function before. It was good. But, in the least version, it gets an error.
![image](https://user-images.githubusercontent.com/20436775/75970439-9d179b80-5ed0-11ea-9442-bc1d0922a5cd.png)
Here is the workflow
[DataTable_XLog.zip](https://github.com/pm4knime/pm4knime-development/files/4292265/DataTable_XLog.zip)
Here is the log
[knime.log](https://github.com/pm4knime/pm4knime-development/files/4292268/knime.log)

**Comment by KFDing** [comment]
hi, @FrankBGao ,
the reason is that the type of timestamp mismatches. The given one is String, but to use Table2XLogConverter, it requires the timestamp in type of DateTime. TO do this, please use the KNIME node called "String to Date/Time". 
Regards
Kefang
