### ISSUE TITLE
RandomClassifyLog not working correctly on receipt log

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#56]
![image](https://user-images.githubusercontent.com/56342194/75886438-8158ba80-5e28-11ea-9158-7aed1ef9f64e.png)

**Comment by KFDing** [comment]
Hi @fit-alessandro-berti ,
I guess you didn't assign any value to the configuration, right?? You really need to stop running it in real practice. But I will try to make it more restricted. 
Kefang
