### ISSUE TITLE
Table2XLog refuses to transform the CSV

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#57]
CSV attached

Configuration:
![image](https://user-images.githubusercontent.com/56342194/75886960-5ae74f00-5e29-11ea-941f-08f0a341b9c4.png)

Problem:
![image](https://user-images.githubusercontent.com/56342194/75886996-68043e00-5e29-11ea-997f-cb24f88e8ed1.png)

[running-example.zip](https://github.com/pm4knime/pm4knime-development/files/4287650/running-example.zip)

**Comment by KFDing** [comment]
Hi, Ale. the reason as shown below is the wrong type format you give. The timestamp should be in DateFormat, you should convert this column at first by using KNIME node "String to Date/Time" . 
As an example, it is like this: 
![image](https://user-images.githubusercontent.com/22542140/75915167-51281080-5e56-11ea-8492-adfb47aba7ff.png)

regards
Kefang
