### ISSUE TITLE
ILP miner has error (PM4KNIME website version)

### ISSUE THREAD

**Issue by FrankBGao** [pm4knime/pm4knime-development#58]
The ILP Miner gets an error.
![image](https://user-images.githubusercontent.com/20436775/75969738-aa805600-5ecf-11ea-9628-e49b7dbc3a01.png)
Here is the workflow
[ILP_Miner.zip](https://github.com/pm4knime/pm4knime-development/files/4292240/ILP_Miner.zip)
Here is the error log
[knime.log](https://github.com/pm4knime/pm4knime-development/files/4292248/knime.log)

**Comment by KFDing** [comment]
Hi @FrankBGao ,
check the workflow, I assume that you just executed the workflow without configuration. I would strongly suggest that you open and reconfigure it. It should work. 
Kefang
