### ISSUE TITLE
Event Log Reader doesn't support knime:// protocol

### ISSUE THREAD

**Issue by stelfrich** [pm4knime/pm4knime-development#59]
When configuring an _Event Log Reader_, the Selected File component of the dialog actually works with `knime://` protocol (start typing `knime://knime.workflow/` to see the error message that this is not a file but a folder) and doesn't complain when pointing it to file using this protocol. During execution, the error following error message is raised:

```
Execute failed: knime:/knime.workflow/data/FileName.xes (No such file or directory)
```

Please note that the reported location is indeed incorrect, i.e. `knime:/knime.workflow` instead of `knime://knime.workflow`.

**Comment by fit-sebastiaan-van-zelst** [comment]
This issue is fixed in the upcoming release
