### ISSUE TITLE
Conversion XLog2Table misses all the desidered attributes

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#6]
As in picture:
![image](https://user-images.githubusercontent.com/56342194/69606405-014dd800-1023-11ea-9d19-5253571eb786.png)
![image](https://user-images.githubusercontent.com/56342194/69606426-0c086d00-1023-11ea-810c-d56c5ce528d8.png)

**Comment by KFDing** [comment]
Hi Ale, 
could you send me also the dataset that you use, so I could have insight on this?? If it is possible, also the exported workflow. 
Thanks, 
Kefang

**Comment by KFDing** [comment]
@fit-alessandro-berti ,

please send me the data set that you test on. Thanks
Kefang

**Comment by KFDing** [comment]
Hi, make the settings right. It should work now.
