### ISSUE TITLE
Problem with Table to Xlog converter, no event log: "loading port contents...", trace omitted

### ISSUE THREAD

**Issue by HaraBeron** [pm4knime/pm4knime-development#63]
I have data which I attached. [sample.csv](https://github.com/pm4knime/pm4knime-core/files/9209441/sample.csv)

 It contains event data. It looks like this:

case_id;activity;timestamp
1;53100;2017-04-07 00:00:00
1;53106;2017-04-07 00:00:00
1;90020;2017-06-14 00:00:00
1;53117;2017-06-14 00:00:00
1;60305;2017-07-11 00:00:00
1;58600;2017-07-12 00:00:00
1;58600;2017-07-12 00:00:00
1;68500;2017-07-12 00:00:00
2;53100;2017-06-23 00:00:00
2;58600;2017-06-23 00:00:00
...

- It is sorted properly, so the missing time is not a problem for me. 
- The case activity are numbers here, however with KNIME I read it in and treat it as string, otherwise I would get an error. 
- There are no trace level attributes, so no additional column with for example costs that vary for each state nor is there an additional column for costs which are the same for an event. So just these three columns.

I have a KNIME workflow which I also attached (I had to zip it, otherwise I could not have attached it). 
[sample.zip](https://github.com/pm4knime/pm4knime-core/files/9209534/sample.zip)

![grafik](https://user-images.githubusercontent.com/68148852/181502191-b4d381a1-77ce-4727-a1a6-145ca7d9bf74.png)

Basic idea is to:

1. use the csv reader to read in the data. I specify the csv reader to read in the activity as string.
2. I use the string to date&time converter to convert the timestamp column to a date&time value type.
3. Then I use the modify time zone node to get the format into the appropriate Zoned Date time format.
4. use the Table to Xlog converter to create an event log

And indeed, it looks fine so far, when I check the output of the third node, the modify time zone:

![grafik](https://user-images.githubusercontent.com/68148852/181502834-1aac853c-1b31-4816-9b6e-61a4e10a10b4.png)

However, when I now try to configure and execute the last node, the Table to Xlog converter it does not work. I right click the Table to Xlog converter and click on configure. Then for "Case Id column" I choose case_id. For "Eventclass Column" I choose activity. For "Life Cycle Column" I choose not available. For  "Time Stamp Column" I choose timestamp. On the "Choose Attributes Set" tab I include everything, for trace attributes and event attributes:

![grafik](https://user-images.githubusercontent.com/68148852/181503402-c7149e01-1998-430d-ace4-88bc044486bc.png)

When I execute the node I get the warning:

>        Unmatch trace attribute values error is detected on the trace, therefore trace is omitted

And when I right click the node I get the messsage "display port content..." and nothing further happens.

I also tried to remove the trace attributes on the choose attribute set tab:

![grafik](https://user-images.githubusercontent.com/68148852/181503699-43a5f83c-94e8-4b4d-9a5a-dda28e5f48cc.png)

But it does not work, as I get the message:

> Make sure the attribute set choice panel includes all the choices in the panel!

and I cannot execute the node.

So where is my mistake? Why is the event log not displayed properly?

I was able to create a xes file for this csv file in Python using PM4PY. When I import this xes directly with the xes reader I can see the event log and further use for example the Alpha Miner. So it seems to be a problem with the Table to Xlog converter or its configuration which I did not do correctly.

**Comment by fit-humam-kourani** [comment]
Dear HaraBeron,

You need to include the caseID in the list of trace attributes and both the eventID and timestamp in the list of event attributes. This means in your case: "case_id" in the list of trace attributes; "activity" and "timestamp" in the list of event attributes. 

I hope this solves the issue!

Best regards,

Humam

**Comment by HaraBeron** [comment]
Thanks a lot for the answer!

Yes, it solved the issue.
