### ISSUE TITLE
Random Classify Event Log does nothing apparently

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#8]
Applying the Event Log Writer after the "Random Classify Event Log" I get an equivalent log (at least it has exactly the same size)

![image](https://user-images.githubusercontent.com/56342194/69607469-9520a380-1025-11ea-989f-70ec7583613c.png)

**Comment by KFDing** [comment]
Check the new version of Random Classify Event Log. The added classification label is a trace attribute in default. So to check it, you need to open the output port event log and check trace. The classification is shown in the right side. 
Kefang
