### ISSUE TITLE
MergeLog ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by fit-alessandro-berti** [pm4knime/pm4knime-development#9]
ERROR MergeLog             0:10       Execute failed: ("ArrayIndexOutOfBoundsException"): 1

![image](https://user-images.githubusercontent.com/56342194/69607654-fb0d2b00-1025-11ea-9d44-7d06e21a3e76.png)

**Comment by s-j-v-zelst** [comment]
I have the same problem when running this without reconfiguring the operator.

**Comment by KFDing** [comment]
Hi, have tested codes, not found such bugs. More details are in need. But before you carry on this step, please make sure it is configuration right. 
Kefang
